-- EduSched schema for PostgreSQL (Neon), ported from the MySQL database.sql.
--   INT AUTO_INCREMENT -> integer GENERATED BY DEFAULT AS IDENTITY
--   ENUM(...)          -> named enum types
--   TIMESTAMP          -> timestamptz
-- plus CHECK constraints, indexes for the hot queries, and modified_classes.sandbox_id.
--
-- Conventions:
--   regular_timetable.day_of_week is ISO: 1 = Monday ... 7 = Sunday (what the frontend assumes).
--   Time ranges are half-open [start, end): a class ending 10:00 does not clash with one starting 10:00.

CREATE TYPE user_role AS ENUM ('student', 'professor');
CREATE TYPE modification_type AS ENUM ('cancelled', 'postponed');

CREATE TABLE users (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    varchar(50)  NOT NULL UNIQUE,
    password    varchar(255) NOT NULL,           -- pbkdf2_sha256$<iterations>$<salt>$<hash>
    email       varchar(100) NOT NULL UNIQUE,
    role        user_role    NOT NULL,
    batch       varchar(50),                     -- students only, e.g. 'CSE-2A'
    created_at  timestamptz  NOT NULL DEFAULT now()
);

CREATE TABLE classrooms (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_number  varchar(20) NOT NULL UNIQUE,
    capacity     integer     NOT NULL CHECK (capacity > 0),
    building     varchar(50)
);

CREATE TABLE courses (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_code   varchar(20)  NOT NULL UNIQUE,
    course_name   varchar(100) NOT NULL,
    professor_id  integer REFERENCES users (id)
);
CREATE INDEX courses_professor_idx ON courses (professor_id);

-- The fixed weekly timetable. The API never writes to it.
CREATE TABLE regular_timetable (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id     integer     NOT NULL REFERENCES courses (id),
    batch         varchar(50) NOT NULL,
    day_of_week   smallint    NOT NULL CHECK (day_of_week BETWEEN 1 AND 7),
    start_time    time        NOT NULL,
    end_time      time        NOT NULL,
    classroom_id  integer REFERENCES classrooms (id),
    CHECK (end_time > start_time)
);
CREATE INDEX regular_timetable_batch_idx ON regular_timetable (batch, day_of_week);
CREATE INDEX regular_timetable_course_idx ON regular_timetable (course_id);
CREATE INDEX regular_timetable_room_idx ON regular_timetable (classroom_id, day_of_week);

-- Overlay of temporary changes. A row replaces its regular class for every
-- occurrence up to valid_until. sandbox_id NULL = visible to everyone;
-- otherwise only to requests carrying that X-Sandbox-Id.
CREATE TABLE modified_classes (
    id                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    regular_class_id   integer NOT NULL REFERENCES regular_timetable (id) ON DELETE CASCADE,
    modification_type  modification_type NOT NULL,
    new_date           date,
    new_start_time     time,
    new_end_time       time,
    new_classroom_id   integer REFERENCES classrooms (id),
    valid_until        date NOT NULL,
    sandbox_id         text CHECK (sandbox_id ~ '^[A-Za-z0-9_-]{16,64}$'),
    created_at         timestamptz NOT NULL DEFAULT now(),
    CHECK (
        modification_type = 'cancelled'
        OR (new_date IS NOT NULL AND new_start_time IS NOT NULL AND new_end_time IS NOT NULL
            AND new_classroom_id IS NOT NULL AND new_end_time > new_start_time
            AND valid_until >= new_date)
    )
);
CREATE INDEX modified_classes_class_idx ON modified_classes (regular_class_id, valid_until);
CREATE INDEX modified_classes_moved_to_idx ON modified_classes (new_date, new_classroom_id)
    WHERE modification_type = 'postponed';
CREATE INDEX modified_classes_expiry_idx ON modified_classes (valid_until);
CREATE INDEX modified_classes_sandbox_idx ON modified_classes (sandbox_id, created_at)
    WHERE sandbox_id IS NOT NULL;
