-- EduSched schema (PostgreSQL on Neon). Multi-tenant: every row except users and
-- sessions belongs to a workspace and disappears with it (ON DELETE CASCADE).
--
-- Conventions:
--   day_of_week is ISO: 1 = Monday ... 7 = Sunday.
--   Times are wall-clock times in the workspace's timezone; ranges are half-open
--   [start, end), so a class ending 10:00 does not clash with one starting 10:00.
--   Changes are per occurrence: (class_id, occurs_on) names one meeting of a weekly class.
--
-- Tables that classes point at carry UNIQUE (workspace_id, id), so classes and changes
-- use composite foreign keys: a class can never reference another workspace's room,
-- whatever the application code does.

CREATE TABLE users (
    id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email          text NOT NULL UNIQUE CHECK (email = lower(email)),
    name           text NOT NULL,
    password_hash  text NOT NULL,                  -- pbkdf2_sha256$<iterations>$<salt>$<hash>
    created_at     timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE workspaces (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug          text NOT NULL UNIQUE CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
    name          text NOT NULL,
    institution   text NOT NULL,
    timezone      text NOT NULL DEFAULT 'Asia/Kolkata',
    days          smallint[] NOT NULL DEFAULT '{1,2,3,4,5}',
    published_at  timestamptz,
    is_demo       boolean NOT NULL DEFAULT false,
    expires_at    timestamptz,                     -- demo copies only
    demo_ip_hash  text,                            -- demo copies only: the per-visitor rate limit counts these
    created_by    integer REFERENCES users (id) ON DELETE SET NULL,
    created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX workspaces_created_by_idx ON workspaces (created_by);
CREATE INDEX workspaces_demo_idx ON workspaces (expires_at) WHERE is_demo;
CREATE INDEX workspaces_demo_ip_idx ON workspaces (demo_ip_hash, created_at) WHERE is_demo;

-- id is SHA-256 (hex) of the cookie token; the token itself is never stored.
-- A session belongs either to a user or to a demo guest (no user row).
CREATE TABLE sessions (
    id                 text PRIMARY KEY,
    user_id            integer REFERENCES users (id) ON DELETE CASCADE,
    demo_workspace_id  integer REFERENCES workspaces (id) ON DELETE CASCADE,
    acting_role        text CHECK (acting_role IN ('coordinator', 'teacher', 'student')),
    acting_id          integer,                    -- the teacher or batch id while acting as one
    created_at         timestamptz NOT NULL DEFAULT now(),
    last_seen_at       timestamptz NOT NULL DEFAULT now(),
    expires_at         timestamptz NOT NULL,
    user_agent         text,
    CHECK ((user_id IS NULL) <> (demo_workspace_id IS NULL))
);
CREATE INDEX sessions_user_idx ON sessions (user_id);
CREATE INDEX sessions_expires_idx ON sessions (expires_at);

CREATE TABLE teachers (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id  integer NOT NULL REFERENCES workspaces (id) ON DELETE CASCADE,
    name          text NOT NULL,
    short         text NOT NULL,
    email         text,
    UNIQUE (workspace_id, short),
    UNIQUE (workspace_id, id)
);

CREATE TABLE members (
    workspace_id  integer NOT NULL REFERENCES workspaces (id) ON DELETE CASCADE,
    user_id       integer NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role          text NOT NULL CHECK (role IN ('coordinator', 'teacher')),
    teacher_id    integer REFERENCES teachers (id) ON DELETE SET NULL,
    joined_at     timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (workspace_id, user_id)
);
CREATE INDEX members_user_idx ON members (user_id);
-- at most one account per teacher row
CREATE UNIQUE INDEX members_teacher_idx ON members (teacher_id) WHERE teacher_id IS NOT NULL;

CREATE TABLE rooms (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id  integer NOT NULL REFERENCES workspaces (id) ON DELETE CASCADE,
    name          text NOT NULL,
    capacity      integer NOT NULL CHECK (capacity > 0),
    building      text,
    kind          text NOT NULL DEFAULT 'lecture' CHECK (kind IN ('lecture', 'lab')),
    UNIQUE (workspace_id, name),
    UNIQUE (workspace_id, id)
);

CREATE TABLE batches (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id  integer NOT NULL REFERENCES workspaces (id) ON DELETE CASCADE,
    name          text NOT NULL,
    size          integer CHECK (size > 0),
    code          text NOT NULL UNIQUE CHECK (code = upper(code)),   -- the class code, e.g. CSE2A-K7QD
    UNIQUE (workspace_id, name),
    UNIQUE (workspace_id, id)
);

CREATE TABLE courses (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id  integer NOT NULL REFERENCES workspaces (id) ON DELETE CASCADE,
    code          text NOT NULL,
    name          text NOT NULL,
    color         smallint NOT NULL DEFAULT 1 CHECK (color BETWEEN 1 AND 8),
    teacher_id    integer REFERENCES teachers (id) ON DELETE SET NULL,   -- the usual teacher; a class may differ
    UNIQUE (workspace_id, code),
    UNIQUE (workspace_id, id)
);

CREATE TABLE periods (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id  integer NOT NULL REFERENCES workspaces (id) ON DELETE CASCADE,
    idx           smallint NOT NULL,
    start_time    time NOT NULL,
    end_time      time NOT NULL,
    label         text,
    is_break      boolean NOT NULL DEFAULT false,
    CHECK (end_time > start_time),
    UNIQUE (workspace_id, idx)
);

-- The weekly timetable. Deleting a room/teacher/batch/course that a class uses is
-- refused: the API names the classes first, and the foreign keys are the backstop.
CREATE TABLE classes (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id  integer NOT NULL REFERENCES workspaces (id) ON DELETE CASCADE,
    course_id     integer NOT NULL,
    batch_id      integer NOT NULL,
    teacher_id    integer NOT NULL,
    room_id       integer NOT NULL,
    day_of_week   smallint NOT NULL CHECK (day_of_week BETWEEN 1 AND 7),
    start_time    time NOT NULL,
    end_time      time NOT NULL,
    CHECK (end_time > start_time),
    UNIQUE (workspace_id, id),
    FOREIGN KEY (workspace_id, course_id) REFERENCES courses (workspace_id, id),
    FOREIGN KEY (workspace_id, batch_id) REFERENCES batches (workspace_id, id),
    FOREIGN KEY (workspace_id, teacher_id) REFERENCES teachers (workspace_id, id),
    FOREIGN KEY (workspace_id, room_id) REFERENCES rooms (workspace_id, id)
);
CREATE INDEX classes_day_idx ON classes (workspace_id, day_of_week);
CREATE INDEX classes_batch_idx ON classes (batch_id);
CREATE INDEX classes_teacher_idx ON classes (teacher_id);
CREATE INDEX classes_room_idx ON classes (room_id);
CREATE INDEX classes_course_idx ON classes (course_id);

-- One change per occurrence. A moved occurrence is booked at to_date, to_start..to_end
-- in to_room_id, and its regular slot is free.
CREATE TABLE changes (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id  integer NOT NULL REFERENCES workspaces (id) ON DELETE CASCADE,
    class_id      integer NOT NULL,
    occurs_on     date NOT NULL,
    kind          text NOT NULL CHECK (kind IN ('cancelled', 'moved')),
    to_date       date,
    to_start      time,
    to_end        time,
    to_room_id    integer,
    reason        text,
    created_by    text NOT NULL,                   -- a name, so it survives the account
    created_at    timestamptz NOT NULL DEFAULT now(),
    UNIQUE (class_id, occurs_on),
    FOREIGN KEY (workspace_id, class_id) REFERENCES classes (workspace_id, id) ON DELETE CASCADE,
    FOREIGN KEY (workspace_id, to_room_id) REFERENCES rooms (workspace_id, id),
    CHECK (
        (kind = 'cancelled' AND to_date IS NULL AND to_start IS NULL AND to_end IS NULL AND to_room_id IS NULL)
        OR (kind = 'moved' AND to_date IS NOT NULL AND to_start IS NOT NULL AND to_end IS NOT NULL
            AND to_room_id IS NOT NULL AND to_end > to_start)
    )
);
CREATE INDEX changes_ws_occurs_idx ON changes (workspace_id, occurs_on);
CREATE INDEX changes_ws_to_idx ON changes (workspace_id, to_date) WHERE kind = 'moved';
CREATE INDEX changes_room_idx ON changes (to_room_id) WHERE kind = 'moved';

CREATE TABLE invites (
    code          text PRIMARY KEY,
    workspace_id  integer NOT NULL REFERENCES workspaces (id) ON DELETE CASCADE,
    role          text NOT NULL CHECK (role IN ('coordinator', 'teacher')),
    teacher_id    integer REFERENCES teachers (id) ON DELETE CASCADE,
    created_by    integer REFERENCES users (id) ON DELETE SET NULL,
    expires_at    timestamptz NOT NULL,
    used_by       integer REFERENCES users (id) ON DELETE SET NULL,
    used_at       timestamptz,
    created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX invites_ws_idx ON invites (workspace_id);

-- code_hash is SHA-256 (hex) of the code; the code itself is shown once, to the coordinator.
CREATE TABLE reset_codes (
    code_hash     text PRIMARY KEY,
    user_id       integer NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    workspace_id  integer NOT NULL REFERENCES workspaces (id) ON DELETE CASCADE,
    expires_at    timestamptz NOT NULL,
    used_at       timestamptz
);
CREATE INDEX reset_codes_user_idx ON reset_codes (user_id);

CREATE TABLE feeds (
    token         text PRIMARY KEY,
    workspace_id  integer NOT NULL REFERENCES workspaces (id) ON DELETE CASCADE,
    kind          text NOT NULL CHECK (kind IN ('batch', 'teacher', 'room')),
    target_id     integer NOT NULL,
    created_by    integer REFERENCES users (id) ON DELETE CASCADE   -- null for a demo guest
);
CREATE INDEX feeds_ws_idx ON feeds (workspace_id, kind, target_id);

CREATE TABLE follows (
    user_id   integer NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    batch_id  integer NOT NULL REFERENCES batches (id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, batch_id)
);
